{{/* Generated by hack/sync-helm-manifests.sh from the +kubebuilder:rbac markers. Do not edit. */}}
{{- define "data-lake-operator.managerRules" -}}
- apiGroups:
  - datalake.opsarray.io
  resources:
  - datalakes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - datalake.opsarray.io
  resources:
  - datalakes/finalizers
  verbs:
  - update
- apiGroups:
  - datalake.opsarray.io
  resources:
  - datalakes/status
  verbs:
  - get
  - patch
  - update
{{- end }}
