# This rule is not used by the project data-lake-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to dataplatform.opsarray.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: data-lake-operator
    app.kubernetes.io/managed-by: kustomize
  name: dataplatform-viewer-role
rules:
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - dataplatforms
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - dataplatforms/status
  verbs:
  - get
