{{/* Generated by hack/sync-helm-manifests.sh from the +kubebuilder:rbac markers. Do not edit. */}}
{{- define "data-platform-operator.managerRules" -}}
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - dataplatforms
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - dataplatforms/finalizers
  verbs:
  - update
- apiGroups:
  - dataplatform.opsarray.io
  resources:
  - dataplatforms/status
  verbs:
  - get
  - patch
  - update
{{- end }}
